### ISSUE TITLE
NFL 401 error

### ISSUE THREAD

**Issue by CallSign-Filter** [edwarddistel/yahoo-fantasy-baseball-reader#110]
I used this all last NFL season to parse out the weekly positional scores for my Fantasy Football League's weekly payouts. This year I am getting nothing but 401 errors. I tried my fork from last year, I tried cloning over again and nothing. 

```
PS C:\Users\Brandon\IdeaProjects\OthersProjects\yahoo-fantasy-baseball-reader> npm run league-prefix

> yahoo-fantasy-baseball-reader@1.0.0 league-prefix
> node src/getLeaguePrefix.js

Error with credentials in makeAPIrequest()/refreshAuthorizationToken(): AxiosError: Request failed with status code 401
Error in getLeaguePrefix(): TypeError: Cannot read properties of undefined (reading 'game')
TypeError: Cannot read properties of undefined (reading 'game')
    at Object.getLeaguePrefix (C:\Users\Brandon\IdeaProjects\OthersProjects\yahoo-fantasy-baseball-reader\src\yahooFantasyBaseball.js:260:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getData (C:\Users\Brandon\IdeaProjects\OthersProjects\yahoo-fantasy-baseball-reader\src\getLeaguePrefix.js:11:19)
PS C:\Users\Brandon\IdeaProjects\OthersProjects\yahoo-fantasy-baseball-reader>
```

I followed all of the steps and have the app registered. Any Ideas?

**Comment by CallSign-Filter** [comment]
Okay I must have messed something up because it wasn't generating the `credentials.json` file over again. So in the fresh one I just downloaded form you (after running the `npm install` on both versions with the new version of the dependencies) I had it generate a new credentials file that I put into the other one and it worked beautifully.

If you or anyone else if curious, I am using this to parse out the weekly positional scores because in my league we have weekly payouts for different positions each week. Also we pay out for most WR points all year and most RB points all year so I have this app generate the points that I copy into a Google Sheet.

And this NFL season is league prefix 414.

Thank you for your help and the beautiful public service that is this app
